### ISSUE TITLE
API returns error when pushing transaction

### ISSUE THREAD

**Issue by marcoalkema** [ShiftNrg/shift#6]
I'm trying to push a transaction to the network, but keep getting back the following error:
` Unknown transaction type undefined'`

Even when I use the following object (taken from the example [here](https://shiftnrg.github.io/shift-js/example/api.html#functions_createTransaction)) it still returns the same error:
```
{
  "type": 0,
  "amount": 100000000000,
  "asset": {},
  "fee": 100000000
  ,"id": '500224999259823996',
  "recipientId": '1859190791819301L',
  "senderPublicKey": '56e106a1d4a53dbe22cac52fefd8fc4123cfb4ee482f8f25a4fc72eb459b38a5',
  "signSignature": '03fdd33bed30270b97e77ada44764cc8628f6ad3bbd84718571695262a5a18baa37bd76a62dd25bc21beacd61eaf2c63af0cf34edb0d191d225f4974cd3aa509',
  "signature": '9419ca3cf11ed2e3fa4c63bc9a4dc18b5001648e74522bc0f22bda46a188e462da4785e5c71a43cfc0486af08d447b9340ba8b93258c4c7f50798060fff2d709',
  "timestamp": 27953413
}
```

Hope you are able to help out.

Kind regards

**Comment by MxShift** [comment]
I'm not sure anyone maintain [shift-js](https://github.com/ShiftNrg/shift-js) you are trying to use. 
As example it refers to http://corenode1.shiftnrg.org:9305 which is outdated.

The easiest way to make a transaction is to use Shift Node API:

`curl -k -H  "Content-Type: application/json" -X PUT -d '{"secondSecret": "second passphrase here or null", "recipientId": "4446910057799968777S", "amount": 100000000000, "secret": "secret passphrase here"}' http://localhost:9305/api/transactions`

Instead of **localhost** you could use any delegates node with open API as example mine `http://5.63.158.45:9305` or the team's `https://wallet.shiftnrg.org` which is better, because it's secured with SSL. 

Or you would like to set up your own node using [this guide](https://www.reddit.com/r/ShiftProject/wiki/guides/delegate). 

The Node API documentation could be find [here](https://github.com/ShiftNrg/API_Documentation).

**Comment by marcoalkema** [comment]
Thank you for your help. It seems that we have been querying the wrong endpoint (`peer/transactions`)...

However, now I've been getting `Missing required property: recipientId` returned, while I do provide it in the object.

**Comment by marcoalkema** [comment]
Resolved this. Thank you for your help.
